services:
  nts:
    container_name: nts
    image: ghcr.io/silvasch/nts:main
    build: .
    ports:
      - 8080:8080
    env_file: .env
    environment:
      - NTS_DATA_DIR=/data
    volumes:
      - ./nts-data:/data
    restart: unless-stopped
