services:
  nts:
    container_name: nts
    image: ghcr.io/silvasch/nts:main
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 9112:9112
    env_file: ../.env
    volumes:
      - ./nts-data:/data
    restart: unless-stopped
